print("╔╗─╔╗╔══╗╔═╗╔╦╗╔══╗")
print("║╚╦╝║╚║║╝║╬║║║║║══╣")
print("╚╗║╔╝╔║║╗║╗╣║║║╠══║")
print("─╚═╝─╚══╝╚╩╝╚═╝╚══╝")
print("───────────────────")
print("ᴛᴏᴏʟs ᴍᴀᴅᴇ ʙʏ ᴢᴄᴀɪɴᴢ")
import time
print()
time.sleep(2)
a=input("TULIS NOMOR HP TARGET: ")
print()
print("----------------------------------------------------------------------------------------------------------")
print()
print("MENGHUBUNGKAN KE SERVER...")
print()
time.sleep(3)
print("TERHUBUNG KE SERVER")
print()
time.sleep(2)
print("MENGIRIMKAN VIRUS...")
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print()
print("MENGIRIM VIRUS KE "+a+" BERHASIL")
time.sleep(1)
print("TERIMA KASIH TELAH MENGGUNAKAN TOOLS INI")